# docker-compose.public.yml - standalone, world accessible
services:

  kafka:
    ports:
      - ${COMPOSE_PORT_PTEXT}:9092   # External access from your host machine:docker-port
      # - ${COMPOSE_PCTRL}:9093 # optional: expose controller if you really need it

networks:
  net:
    driver: bridge
    name: ${COMPOSE_LEAD}-${COMPOSE_CNET}