services:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${COMPOSE_LEAD}-${COMPOSE_NAME}-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092   # Points to kafka service
      AUTH_TYPE: LOGIN_FORM                           # Enables the login screen
      SPRING_SECURITY_USER_NAME: ${COMPOSE_APP_USER}
      SPRING_SECURITY_USER_PASSWORD: ${COMPOSE_APP_PASS}
    depends_on:
      - kafka
    restart: unless-stopped